###
// user 회원가입
POST http://localhost:3000/auth/signUp/user
Content-Type: application/json

{
  "nickname": "test14",
  "email": "test14@example.com",
  "password": "testpassword14!"
}

###
// trainer 회원가입
POST http://localhost:3000/auth/signUp/trainer
Content-Type: application/json

{
  "nickname": "test13",
  "email": "test13@example.com",
  "password": "testpassword13!"
}

###
// 로그인
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test14@example.com",
  "password": "testpassword14!"
}

###
// access token 재발급
POST http://localhost:3000/auth/token/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0NTg1YjY0MC02OTBmLTRhY2YtYWUyZS1hZGM3Zjk1N2M2MGMiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczNjI5NzUwNiwiZXhwIjoxNzM2MzAxMTA2fQ.t3zHamdeiA1eW7HLiSIAy67pPwGvjtRRj_PhgjYymjM

###
// user 단일 조회하기
GET http://localhost:3000/users/0852ac4f-20b8-4d8f-b539-78a18438d158
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwODUyYWM0Zi0yMGI4LTRkOGYtYjUzOS03OGExODQzOGQxNTgiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczNjQwOTg1NSwiZXhwIjoxNzM3NjE5NDU1fQ.8BMk5GTVbzCvOt3Z2N35eNK1Zt4m3pWfuOmLxfRJYjY