###
// user 회원가입
POST http://localhost:3000/auth/signUp/user
Content-Type: application/json

{
  "nickname": "user03",
  "email": "user03@example.com",
  "password": "a123456."
}

### 로그인 (일반유저)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "user01@example.com",
  "password": "a123456."
}

### Lesson 요청 등록 #OFFLINE
POST http://localhost:3000/lessons
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTlmYzM4Ni1kMWE3LTQ0MzAtYTM3ZC05ZDFjNWJkYWZkM2YiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczNjgzMjc4MywiZXhwIjoxNzM4MDQyMzgzfQ.OOWLlg7tp8EmhI6onP0y4SPPjRViRsVDcRE8LG-9FsA

{
  "lessonType": "FITNESS",
  "lessonSubType": "PILATES",
  "startDate": "2024-01-20T10:00:00.000Z",
  "endDate": "2024-01-25T23:59:59.000Z",
  "lessonCount": 5,
  "lessonTime": 40,
  "quoteEndDate": "2024-01-24T23:59:59.000Z",
  "locationType": "OFFLINE",
  "postcode": "13529",
  "roadAddress": "경기 성남시 분당구 판교역로 166",
  "detailAddress": "101호"
}

### Lesson 요청 등록 #ONLINE
POST http://localhost:3000/lessons
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTlmYzM4Ni1kMWE3LTQ0MzAtYTM3ZC05ZDFjNWJkYWZkNGQiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczNjgyMjMwMiwiZXhwIjoxNzM4MDMxOTAyfQ.qjr21AVEAoG7JdhIJM0b7iLLpbf_uojBNy5mtAcdAMI

{
  "lessonType": "FITNESS",
  "lessonSubType": "YOGA",
  "startDate": "2024-01-15T10:00:00.000Z",
  "endDate": "2024-01-15T23:59:59.000Z",
  "lessonCount": 1,
  "lessonTime": 8,
  "quoteEndDate": "2024-01-14T23:59:59.000Z",
  "locationType": "ONLINE",
  "postcode": "",
  "roadAddress": "",
  "detailAddress": ""
}

### Lesson 요청 취소
PATCH http://localhost:3000/lessons/777f2bf6-0bb9-49b6-9a19-a097c24c1911/cancel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTlmYzM4Ni1kMWE3LTQ0MzAtYTM3ZC05ZDFjNWJkYWZkM2YiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczNjQwODE1OCwiZXhwIjoxNzM3NjE3NzU4fQ.sQdttuIRl8cEUuoEuXz_zjsKiiPOYzdvaTommGmaKGM

###  Lesson 요청 상세 조회
GET http://localhost:3000/lessons/777f2bf6-0bb9-49b6-9a19-a097c24c1911

### 요청 레슨 목록 조회
GET http://localhost:3000/lessons?page=1&limit=2&order=start_date&sort=asc

###
GET http://localhost:3000/lessons?lesson_type=SPORTS,FITNESS&location_type=ONLINE,OFFLINE&page=1&limit=10

###
GET http://localhost:3000/lessons?status=CANCELED&page=1&limit=5

### 나의 요청 레슨 목록 조회
GET http://localhost:3000/lessons/me?status=PENDING&page=1&limit=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTlmYzM4Ni1kMWE3LTQ0MzAtYTM3ZC05ZDFjNWJkYWZkM2YiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczNjc2MTg4NSwiZXhwIjoxNzM3OTcxNDg1fQ.iYo9-b9L3nmI22WnENJSSgnumVUZzIo1W3N68JybHac

###
GET http://localhost:3000/lessons/me?status=CANCELED
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzYzBlNmEzNC0zMzZlLTQ0MGUtOTY5Zi0wYWEwMTk5YzU5MTUiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczNjQxMDU1OCwiZXhwIjoxNzM3NjIwMTU4fQ.LfZOl8h14ZZjHqPYxMOWffZkufdvWG58XKZsxHlMNYI