### user 회원가입
POST http://localhost:3000/auth/signUp/user
Content-Type: application/json

{
  "nickname": "user99",
  "email": "user99@example.com",
  "password": "a123456!"
}

### trainer 회원가입
POST http://localhost:3000/auth/signUp/trainer
Content-Type: application/json

{
  "nickname": "user999",
  "email": "user999@example.com",
  "password": "a123456!"
}

### 로그인 (일반유저)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "user99@example.com",
  "password": "a123456!"
}

### 로그인 (트레이너)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "user999@example.com",
  "password": "a123456!"
}

### 트레이너 찜하기
POST http://localhost:3000/trainers/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5ODBiNDhkMS1iNGFjLTQwZDQtYTIxZS03NTVlOGZlZTkyNzQiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczNjcwMTI0NSwiZXhwIjoxNzM3OTEwODQ1fQ.k7gbdCAgaD4RStBoQ6ayhYOkIhKpn4ZE4cIYoKI-p0g

{
  "trainerId": "df0f0599-a697-4211-b180-a016d9275120"
}

### 찝한 트레이너 삭제
DELETE http://localhost:3000/trainers/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5ODBiNDhkMS1iNGFjLTQwZDQtYTIxZS03NTVlOGZlZTkyNzQiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczNjcwMDU2NCwiZXhwIjoxNzM3OTEwMTY0fQ.8gAkhaTtHgcwCsI214t4RSualX8GUO4VDu5AU8ArWkQ

{
  "trainerId": "df0f0599-a697-4211-b180-a016d9275120"
}